[package]
name = "raft"
version = "0.1.7"
edition = "2024"
license = "MIT"
keywords = ["semantic-web", "ontology", "dolfin", "knowledge-graph", "language"]
categories = ["compilers", "parsing"]
description = "command-line interface for working with Dolfin ontology files. It provides tools for linting, formatting, building, and managing Dolfin packages (`.dlf` files)."
homepage = "https://www.dolfin.fr"
repository = "https://github.com/dolfin-team/raft"

[[bin]]
name = "raft"
path = "src/main.rs"

[dependencies]
rowl = { version = "0.1.6", features = ["fs"] }
dolfin-lint = "0.1.6"
dolfin-diagnostic = "0.1.3"
irukame = { path = "../irukame" }
mekarui = { path = "../mekarui" }
clap = { version = "4.5.59", features = ["derive", "cargo"]}
clap_complete = "4.5.66"
thiserror = "2.0.18"
cliclack = "0.5"
serde_json = "1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true


